# Generated by Django 4.2.17 on 2024-12-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_projects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "late_entry_time",
                    models.CharField(max_length=255, verbose_name="Late Entry Time"),
                ),
                (
                    "early_exit_time",
                    models.CharField(max_length=255, verbose_name="Early Exit Time"),
                ),
                ("penalty", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserAttendance",
                "verbose_name_plural": "UserAttendances",
                "unique_together": {("user", "date")},
            },
        ),
    ]
