# Generated by Django 5.1.4 on 2024-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('junior', 'Yetakchi  mutaxassis'), ('middle', 'Bosh mutaxassis'), ('senior', 'Loyiha rahbari')], default='junior', max_length=20),
        ),
    ]
