# Generated by Django 4.2.17 on 2024-12-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtasks_taskassignee_tasks_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTasksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Sub Task Category',
                'verbose_name_plural': 'Sub Task Categories',
            },
        ),
        migrations.AddField(
            model_name='subtasks',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='tasks.subtaskscategory'),
        ),
    ]
