# Generated by Django 4.2.17 on 2024-12-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtaskscategory_subtasks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignee',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigne Date'),
        ),
    ]
