# Generated by Django 4.2.18 on 2025-01-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskassignee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignee',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating'),
        ),
    ]
